# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdf8b4379a4b98d6b0d5fb7cc491e1f2d70b1d849f5cdcdbc8a481ed58280a695a40e21e2d88b28b8b3d7cc71efeea37948e903df3fcb057392e038e77bc9306

test:
  secret_key_base: d4bc790cae2f4f055bb4b0587b48747f3bc343907f528c081bcd5a442dee2b89e3033b58d7d27b30e7b67d202753c5ab28426b3cffe48e01179cc8175ef915ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
